- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - vim
      - dconf-cli # necessary to use dconf
      - python3-psutil # necessary to use dconf
      - sane # scanner
      - hplip-gui # hp printer / scanner
      - notepadqq

      # tests
      - neofetch
      
      # dev
      - libtool
      
- name: copy wallpaper file
  copy:
    src: files/wallpaper_1920x1080_cmatrix.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: copy .bash_aliases file
  copy:
    src: files/bash_aliases
    dest: "/home/{{ username }}/.bash_aliases"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy .vimrc file
  copy:
    src: files/vimrc
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: set wallpaper
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

# https://protonvpn.com/support/official-linux-vpn-debian/
- name: Install proton vpn .deb package from the internet 
  ansible.builtin.apt:
    deb: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3-2_all.deb

- name: Install proton-vpn-gnome-desktop
  apt:
    name: proton-vpn-gnome-desktop

# https://www.google.com/linuxrepositories/
# https://michaelheap.com/ansible-installing-google-chrome/

# https://openvpn.net/cloud-docs/owner/connectors/connector-user-guides/openvpn-3-client-for-linux.html

