- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - vim
      - dconf-cli # necessary to use dconf
      - python3-psutil # necessary to use dconf
      
- name: copy wallpaper file
  copy:
    src: files/wallpaper_1600x900_linux.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: copy .bash_aliases file
  copy:
    src: files/bash_aliases
    dest: /home/user1/.bash_aliases
    owner: user1
    group: user1

- name: copy .vimrc file
  copy:
    src: files/vimrc
    dest: /home/user1/.vimrc
    owner: user1
    group: user1

- name: set wallpaper
  become_user: user1
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position
  become_user: user1
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
