- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - vim
      - dconf-cli # necessary to use dconf
      - python3-psutil # necessary to use dconf
      - sane # scanner
      - hplip-gui # hp printer / scanner

      # tests
      - neofetch
      
      # dev
      - libtool
      
- name: copy wallpaper file
  copy:
    src: files/wallpaper_1920x1080_cmatrix.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: copy .bash_aliases file
  copy:
    src: files/bash_aliases
    dest: "/home/{{ username }}/.bash_aliases"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy .vimrc file
  copy:
    src: files/vimrc
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: set wallpaper
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
