- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - dconf-cli
      

- name: copy wallpaper file
  copy:
    src: files/wallpaper.png
    dest: /usr/share/backgrounds/wallpaper_1600x900_linux.png
    owner: root
    group: root

- name: set wallpaper
  become_user: user1
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/wallpaper_1600x900_linux.png'"

- name: set wallpaper position
  become_user: user1
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
