"Disable compatibility with vi which can cause unexpected issues.
set nocompatible

"Stuff
syntax on

"Files and Plugins
filetype on
filetype plugin on
filetype indent on

"Search
set incsearch
set hlsearch
set smartcase

"Text
"replaces tabs with spaces
set expandtab
set shiftwidth=2
set tabstop=2
set ai
set si

"UI
set noerrorbells
set ruler
set cmdheight=1
set number
set relativenumber

"Styles
colorscheme desert

set nobackup
set nowb
set noswapfile

"training
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
